export const translations = {
    en: {
        //Login, Register
        register: "Register",
        registering: "Registering...",
        login: "Login",
        logging_in: "Logging in...",
        register_ok: "Registration successful! You can now log in.",
        logout: "Logout",
        profile: "Profile",
        match_history: "Match History",
        language: "Language",
        invalid_user_or_password: "Invalid username or password",
        invalid_user_or_email: "Invalid username or email",
        invalid_password: "Invalid password",
        login_success: "Login successful",
        //User Profile & Game Lobby
        username: "Username",
        new_username: "New username",
        avatar: "Avatar",
        new_avatar: "New avatar URL",
        password: "Password",
        new_password: "New password",
        email: "Email",
        new_email: "New email",
        confirm_password: "Confirm password",
        submit: "Submit",
        edit_profile: "Edit profile",
        stats: "Statistics",
        victories: "Victories",
        defeats: "Defeats",
        //2FA + Message
        two_factor_authentication: "Two-Factor Authentication",
        enable_2fa: "Enable 2FA",
        disable_2fa: "Disable 2FA",
        enter_2fa: "Enter your authentication code",
        verify: "Verify",
        enter_email_2fa: "Enter your email for 2FA",
        enter_phone_2fa: "Enter your phone number",
        no_value_provided: "Please enter a value.",
        error_prefix: "Error: ",
        two_fa_enabled_success: "2FA successfully enabled!",
        two_fa_is_enabled: "2FA is enabled",
        disable: "Disable",
        two_fa_setup_in_progress: "2FA setup in progress...",
        cancel: "Cancel",
        enabled: "Enabled",
        two_fa_is_disabled: "2FA is disabled.",
        enable: "Enable",
        code_must_be_six_digits: "The code must contain exactly 6 digits.",
        scan_qr_warning: "Make sure to scan the QR code with your Google Authenticator app before refreshing or navigating away from this page.",
        scan_qr_instruction: "Scan the QR code and enter the generated code. Keep it in your Google Authenticator app for future logins.",
        qr_activation_error: "Error enabling QR code.",
        method_not_selected: "No 2FA method selected.",
        two_fa_required: "2FA required",
        enter_2fa_code: "Enter the 2FA code",
        login_success_2fa: "Login successful with 2FA!",
        //Friends
        friends: "Friends",
        add_friend: "Add friend",
        your_friends: "Your friends",
        pending_friends: "Pending friends",
        remove_friend: "Remove friend",
        save_changes: "Save changes",
        //Languages
        english: "English",
        french: "French",
        spanish: "Spanish",
        //Game modes
        tournament: "Tournament",
        quick_match: "Quick Match",
        enter_player_name: "Enter player name",
        how_many_players: "How many player(s):",
        play: "PLAY",
        ready: "READY",
        //Errors and success messages
        invalid_username: "Invalid username",
        invalid_email: "Invalid email",
        invalid_password_format: "Invalid password format",
        username_or_email_taken: "Username or email is already taken",
        passwords_do_not_match: "Passwords do not match",
        errors_prefix: "Errors:",
        server_error_prefix: "Server error:",
        profile_not_found: "Profile not found",
        profile_updated: "Profile updated!",
        missing_user_id: "Error: Cannot find user ID",
        network_error: "Network error",
        logout_missing_user_id: "Cannot logout: missing user ID. Try refreshing the page and retry.",
        logout_success: "Logout successful",
        logout_user_not_found: "Logout: user not found on server — local session cleared.",
        logout_error: "Error logging out:",
        error_404_title: "Page not found",
        error_404_text: "The page you are looking for does not exist.",
    },
    fr: {
        //Inscription, Connexion
        register: "S'inscrire",
        registering: "Inscription en cours...",
        register_ok: "Inscription réussie ! Vous pouvez maintenant vous connecter.",
        login: "Connexion",
        logging_in: "Connexion en cours...",
        logout: "Déconnexion",
        profile: "Profil",
        match_history: "Historique des matchs",
        language: "Langue",
        invalid_user_or_password: "Nom d'utilisateur ou mot de passe invalide",
        invalid_user_or_email: "Nom d'utilisateur ou email invalide",
        invalid_password: "Mot de passe invalide",
        login_success: "Connexion réussie",
        //Profil utilisateur & Lobby de jeu
        username: "Nom d'utilisateur",
        new_username: "Nouveau nom d'utilisateur",
        avatar: "Photo de profil",
        new_avatar: "Nouvelle URL de la photo de profil",
        password: "Mot de passe",
        new_password: "Nouveau mot de passe",
        email: "Email",
        new_email: "Nouvel email",
        confirm_password: "Confirmer le mot de passe",
        submit: "Valider",
        edit_profile: "Modifier le profil",
        stats: "Statistiques",
        victories: "Victoires",
        defeats: "Défaites",
        //2FA + Messages
        two_factor_authentication: "Authentification à deux facteurs",
        enable_2fa: "Activer la 2FA",
        disable_2fa: "Désactiver la 2FA",
        enter_2fa: "Entrez votre code d'authentification",
        verify: "Vérifier",
        enter_email_2fa: "Entrez votre email pour la 2FA",
        enter_phone_2fa: "Entrez votre numéro de téléphone",
        no_value_provided: "Veuillez entrer une valeur.",
        error_prefix: "Erreur : ",
        two_fa_enabled_success: "2FA activée avec succès !",
        two_fa_is_enabled: "La 2FA est activée",
        disable: "Désactiver",
        two_fa_setup_in_progress: "Configuration de la 2FA en cours...",
        cancel: "Annuler",
        enabled: "Activée",
        two_fa_is_disabled: "La 2FA est désactivée.",
        enable: "Activer",
        code_must_be_six_digits: "Le code doit contenir exactement 6 chiffres.",
        scan_qr_warning: "Assurez-vous de scanner le QR code avec votre application Google Authenticator avant de rafraîchir ou de quitter la page.",
        scan_qr_instruction: "Scannez le QR code et entrez le code généré. Gardez-le dans votre application Google Authenticator pour vos futures connexions.",
        qr_activation_error: "Erreur lors de l'activation du QR code.",
        method_not_selected: "Aucune méthode 2FA sélectionnée.",
        two_fa_required: "2FA requise",
        enter_2fa_code: "Entrez le code 2FA",
        login_success_2fa: "Connexion réussie avec 2FA !",
        //Amis
        friends: "Amis",
        add_friend: "Ajouter un ami",
        your_friends: "Vos amis",
        pending_friends: "Amis en attente",
        remove_friend: "Retirer un ami",
        save_changes: "Enregistrer les modifications",
        //Langues
        english: "Anglais",
        french: "Français",
        spanish: "Espagnol",
        //Modes de jeu
        tournament: "Tournoi",
        quick_match: "Partie rapide",
        enter_player_name: "Entrez le nom du joueur",
        how_many_players: "Combien de joueur(s) :",
        play: "JOUER",
        ready: "PRÊT",
        //Erreur s et messages de succès
        invalid_username: "Nom d'utilisateur invalide",
        invalid_email: "Email invalide",
        invalid_password_format: "Format du mot de passe invalide",
        username_or_email_taken: "Le nom d'utilisateur ou l'email est déjà pris",
        passwords_do_not_match: "Les mots de passe ne correspondent pas",
        errors_prefix: "Erreurs :",
        server_error_prefix: "Erreur serveur :",
        profile_not_found: "Profile introuvable",
        profile_updated: "Profil mis à jour !",
        missing_user_id: "Erreur : ID utilisateur introuvable",
        network_error: "Erreur réseau",
        logout_missing_user_id: "Impossible de se déconnecter : ID utilisateur manquant. Veuillez rafraîchir la page et réessayer.",
        logout_success: "Déconnexion réussie",
        logout_user_not_found: "Déconnexion : utilisateur introuvable sur le serveur — session locale supprimée.",
        logout_error: "Erreur lors de la déconnexion :",
        error_404_title: "Page introuvable",
        error_404_text: "La page que vous recherchez n'existe pas.",
    },
    es: {
        //Registro, Inicio de sesión
        register: "Registrar",
        registering: "Registrando...",
        register_ok: "¡Registro exitoso! Ahora puedes iniciar sesión.",
        login: "Iniciar sesión",
        logging_in: "Iniciando sesión...",
        logout: "Cerrar sesión",
        profile: "Perfil",
        match_history: "Historial de partidas",
        language: "Idioma",
        invalid_user_or_password: "Usuario o contraseña inválida",
        invalid_user_or_email: "Usuario o correo electrónico inválido",
        invalid_password: "Contraseña inválida",
        login_success: "Inicio de sesión exitoso",
        //Perfil de usuario y lobby de juego
        username: "Usuario",
        new_username: "Nuevo nombre de usuario",
        avatar: "Avatar",
        new_avatar: "Nueva URL del avatar",
        password: "Contraseña",
        new_password: "Nueva contraseña",
        email: "Correo electrónico",
        new_email: "Nuevo correo electrónico",
        confirm_password: "Confirmar contraseña",
        submit: "Enviar",
        edit_profile: "Editar perfil",
        stats: "Estadísticas",
        victories: "Victorias",
        defeats: "Derrotas",
        //2FA + Mensajes
        two_factor_authentication: "Autenticación de dos factores",
        enable_2fa: "Activar 2FA",
        disable_2fa: "Desactivar 2FA",
        enter_2fa: "Introduce tu código de autenticación",
        verify: "Verificar",
        enter_email_2fa: "Introduce tu correo para la 2FA",
        enter_phone_2fa: "Introduce tu número de teléfono",
        no_value_provided: "Por favor introduce un valor.",
        error_prefix: "Error: ",
        two_fa_enabled_success: "¡2FA activada con éxito!",
        two_fa_is_enabled: "La 2FA está activada",
        disable: "Desactivar",
        two_fa_setup_in_progress: "Configuración de 2FA en progreso...",
        cancel: "Cancelar",
        enabled: "Activada",
        two_fa_is_disabled: "La 2FA está desactivada.",
        enable: "Activar",
        code_must_be_six_digits: "El código debe contener exactamente 6 dígitos.",
        scan_qr_warning: "Asegúrate de escanear el código QR con Google Authenticator antes de actualizar o salir de la página.",
        scan_qr_instruction: "Escanea el código QR e introduce el código generado. Guárdalo en tu Google Authenticator para futuros inicios de sesión.",
        qr_activation_error: "Error activando el código QR.",
        method_not_selected: "No se seleccionó ningún método 2FA.",
        two_fa_required: "2FA requerida",
        enter_2fa_code: "Introduce el código 2FA",
        login_success_2fa: "¡Inicio de sesión exitoso con 2FA!",
        //Amigos
        friends: "Amigos",
        add_friend: "Añadir amigo",
        your_friends: "Tus amigos",
        pending_friends: "Amigos pendientes",
        remove_friend: "Eliminar amigo",
        save_changes: "Guardar cambios",
        //Idiomas
        english: "Inglés",
        french: "Francés",
        spanish: "Español",
        //Modos de juego
        tournament: "Torneo",
        quick_match: "Partida rápida",
        enter_player_name: "Ingresa el nombre del jugador",
        how_many_players: "¿Cuántos jugadores?",
        play: "JUGAR",
        ready: "LISTO",
        //Errores y mensajes de éxito
        invalid_username: "Usuario inválido",
        invalid_email: "Correo inválido",
        invalid_password_format: "Formato de contraseña inválido",
        username_or_email_taken: "El nombre de usuario o el correo ya están en uso",
        passwords_do_not_match: "Las contraseñas no coinciden",
        errors_prefix: "Errores:",
        server_error_prefix: "Error del servidor:",
        profile_not_found: "Perfil no encontrado",
        profile_updated: "¡Perfil actualizado!",
        missing_user_id: "Error: no se encontró el ID del usuario",
        network_error: "Error de red",
        logout_missing_user_id: "No se puede cerrar sesión: falta el ID de usuario. Recarga la página e inténtalo de nuevo.",
        logout_success: "Cierre de sesión exitoso",
        logout_user_not_found: "Cierre de sesión: usuario no encontrado en el servidor — sesión local eliminada.",
        logout_error: "Error al cerrar sesión:",
        error_404_title: "Página no encontrada",
        error_404_text: "La página que buscas no existe.",
    },
};
