export const translations = {
    en: {
        //Login, Register
        register: "Register",
        registering: "Registering...",
        login: "Login",
        logging_in: "Logging in...",
        register_ok: "Registration successful! You can now log in.",
        logout: "Logout",
        profile: "Profile",
        match_history: "Match History",
        language: "Language",
        invalid_user_or_password: "Invalid username or password",
        invalid_user_or_email: "Invalid username or email",
        invalid_password: "Invalid password",
        login_success: "Login successful",
        oauth42: "Login with 42",
        //User Profile & Game Lobby
        username: "Username",
        new_username: "New username",
        avatar: "Avatar",
        new_avatar: "New avatar URL",
        change_avatar: "Change Avatar",
        upload_avatar: "Upload Avatar",
        password: "Password",
        new_password: "New password",
        email: "Email",
        new_email: "New email",
        confirm_password: "Confirm password",
        submit: "Submit",
        edit_profile: "Edit profile",
        edit: "Edit",
        stats: "Statistics",
        victories: "Victories",
        defeats: "Defeats",
        win_tournament: " won the tournament!",
        win_this: " win this ",
        point: " point!",
        //2FA + Message
        logout_btn: "Logout",
        draw: "Draw",
        two_factor_authentication: "2FA Authentication",
        enable_2fa: "Enable 2FA",
        disable_2fa: "Disable 2FA",
        failed_enable: "Failed to enable 2FA. Please try again.",
        enter_2fa: "Enter your authentication code",
        verify: "Verify",
        enter_email_2fa: "Enter your email for 2FA",
        enter_phone_2fa: "Enter your phone number",
        no_value_provided: "Please enter a value.",
        error_prefix: "Error: ",
        scan_qr: "Scan the QR code and enter the generated code...",
        error_qr: "Server did not return QR code",
        two_fa_enabled_success: "2FA successfully enabled!",
        two_fa_is_enabled: "2FA is enabled",
        disable: "Disable",
        two_fa_setup_in_progress: "2FA setup in progress...",
        cancel: "Cancel",
        missing_2fa_code: "Missing 2FA code.",
        enabled: "Enabled",
        two_fa_is_disabled: "2FA is disabled.",
        enable: "Enable",
        code_must_be_six_digits: "The code must contain exactly 6 digits.",
        scan_qr_warning: "Make sure to scan the QR code with your Google Authenticator app before refreshing or navigating away from this page.",
        scan_qr_instruction: "Scan the QR code and enter the generated code. Keep it in your Google Authenticator app for future logins.",
        qr_activation_error: "Error enabling QR code.",
        method_not_selected: "No 2FA method selected.",
        twofa_not_init: "2FA module not initialized. Call init2FA() first.",
        two_fa_required: "2FA required",
        enter_2fa_code: "Enter the 2FA code",
        six_numbers_requiered: "The code must contain exactly 6 digits.",
        login_success_2fa: "Login successful with 2FA!",
        only_png: "Only PNG images are allowed.",
        image_too_heavy: "Image is too heavy (max 2MB).",
        //Friends
        friends: "Friends",
        friend_list: "Friend list",
        add_friend: "•︎ Add friend",
        your_friends: "•︎ Your friends",
        pending_friends: "•︎ Pending friends",
        remove_friend: "Remove friend",
        ask_username: "Enter the username of the friend to add:",
        friend_request_sent: "Friend request sent!",
        save_changes: "Save changes",
        failed_friend_request: "Failed to send friend request",
        cannot_send_request_to_yourself: "You cannot send a friend request to yourself",
        friend_request_already_exists: "Friend request already exists",
        already_friends: "Already friends",
        no_friends_yet: "No friends yet",
        no_pending_requests: "No pending requests",
        friends_request_accepted: "Friend request accepted!",
        friends_request_rejected: "Friend request rejected!",
        //Languages
        english: "English",
        french: "French",
        spanish: "Spanish",
        //Game modes
        tournament: "Tournament",
        quick_match: "Quick Match",
        enter_player_name: "Enter player name",
        how_many_players: "How many player(s):",
        semifinal_1: "Semifinal 1",
        semifinal_2: "Semifinal 2",
        player_1: "Player 1",
        player_2: "Player 2",
        player_3: "Player 3",
        player_4: "Player 4",
        champion: "Champion",
        play: "PLAY",
        ready: "READY",
        //Errors and success messages
        failed_update_avatar: "Failed to update avatar",
        user_not_found: "User not found",
        no_match_history: "No matches yet",
        failed_fetch_history: "Failed to fetch match history",
        invalid_username: "Invalid username",
        invalid_email: "Invalid email",
        invalid_password_format: "Password must have 8 characters, one uppercase letter and one number, and no spaces allowed",
        username_or_email_taken: "Username or email is already taken",
        failed_accept_request: "Failed to accept request",
        passwords_do_not_match: "Passwords do not match",
        must_login: "You must be logged in",
        failed_reject_request: "Error rejecting request",
        failed_remove_friend: "Failed to remove friend",
        server_error_prefix: "Server error:",
        profile_not_found: "Profile not found",
        profile_updated: "Profile updated!",
        missing_user_id: "Error: Cannot find user ID",
        network_error: "Network error",
        logout_missing_user_id: "Cannot logout: missing user ID. Try refreshing the page and retry.",
        logout_success: "Logout successful",
        failed_fetch_friends: "Failed to fetch friends",
        logout_user_not_found: "Logout: user not found on server — local session cleared.",
        logout_error: "Error logging out:",
        error_404_title: "Page not found",
        error_404_text: "The page you are looking for does not exist.",
        user_no_password: "User has no password (OAuth account)"
    },
    fr: {
        //Inscription, Connexion
        register: "S'inscrire",
        registering: "Inscription en cours...",
        register_ok: "Inscription réussie ! Vous pouvez maintenant vous connecter.",
        login: "Connexion",
        logging_in: "Connexion en cours...",
        logout: "Déconnexion",
        profile: "Profil",
        match_history: "Historique des matchs",
        language: "Langue",
        invalid_user_or_password: "Nom d'utilisateur ou mot de passe invalide",
        invalid_user_or_email: "Nom d'utilisateur ou email invalide",
        invalid_password: "Mot de passe invalide",
        login_success: "Connexion réussie",
        oauth42: "Connexion avec 42",
        //Profil utilisateur & Lobby de jeu
        username: "Nom d'utilisateur",
        new_username: "Nouveau nom d'utilisateur",
        avatar: "Photo de profil",
        new_avatar: "Nouvelle URL de la photo de profil",
        change_avatar: "Changer la photo de profil",
        upload_avatar: "Importer une photo de profil",
        password: "Mot de passe",
        new_password: "Nouveau mot de passe",
        email: "Email",
        new_email: "Nouvel email",
        confirm_password: "Confirmer le mot de passe",
        submit: "Valider",
        edit_profile: "Modifier le profil",
        edit: "Modifier",
        stats: "Statistiques",
        victories: "Victoires",
        defeats: "Défaites",
        win_tournament: " remporte le tournoi !",
        win_this: " gagne avec ",
        point: " point(s)!",
        //2FA + Messages
        logout_btn: "Deconnexion",
        draw: "Egalite",
        two_factor_authentication: "2FA Authentification",
        enable_2fa: "Activer la 2FA",
        disable_2fa: "Désactiver la 2FA",
        failed_enable: "Echec de l'activation de la 2FA. Veuillez reessayer.",
        enter_2fa: "Entrez votre code d'authentification",
        verify: "Vérifier",
        enter_email_2fa: "Entrez votre email pour la 2FA",
        enter_phone_2fa: "Entrez votre numéro de téléphone",
        no_value_provided: "Veuillez entrer une valeur.",
        error_prefix: "Erreur : ",
        missing_2fa_code: "Code 2FA manquant.",
        two_fa_enabled_success: "2FA activée avec succès !",
        two_fa_is_enabled: "La 2FA est activée",
        error_qr: "Le serveur n'a pas renvoye le QR code",
        scan_qr: "Scannez le QR code et entrez le code généré...",
        disable: "Désactiver",
        two_fa_setup_in_progress: "Configuration de la 2FA en cours...",
        cancel: "Annuler",
        enabled: "Activée",
        two_fa_is_disabled: "La 2FA est désactivée.",
        enable: "Activer",
        code_must_be_six_digits: "Le code doit contenir exactement 6 chiffres.",
        scan_qr_warning: "Assurez-vous de scanner le QR code avec votre application Google Authenticator avant de rafraîchir ou de quitter la page.",
        scan_qr_instruction: "Scannez le QR code et entrez le code généré. Gardez-le dans votre application Google Authenticator pour vos futures connexions.",
        qr_activation_error: "Erreur lors de l'activation du QR code.",
        method_not_selected: "Aucune méthode 2FA sélectionnée.",
        twofa_not_init: "Le module 2FA n'est pas initialisee. Utiliser Init2FA() d'abord.",
        two_fa_required: "2FA requise",
        enter_2fa_code: "Entrez le code 2FA",
        six_numbers_requiered: "Le code doit contenir exactement 6 chiffres.",
        login_success_2fa: "Connexion réussie avec 2FA !",
        only_png: "Seules les images PNG sont autorisées.",
        image_too_heavy: "L'image est trop lourde (max 2MB).",
        //Amis
        friends: "Amis",
        friend_list: "Liste d'amis",
        add_friend: "Ajouter un ami",
        your_friends: "Vos amis",
        pending_friends: "Amis en attente",
        remove_friend: "Retirer un ami",
        ask_username: "Entrez le nom d'utilisateur de l'ami à ajouter :",
        friend_request_sent: "Demande d'ami envoyée !",
        failed_friend_request: "Echec de l'envoi de la demande d'ami",
        cannot_send_request_to_yourself: "Vous ne pouvez pas envoyer une demande d'ami à vous-même",
        friend_request_already_exists: "La demande d'ami existe déjà",
        already_friends: "Déjà amis",
        no_friends_yet: "Aucun ami pour le moment",
        no_pending_requests: "Aucune demande en attente",
        friends_request_accepted: "Demande d'ami acceptée !",
        friends_request_rejected: "Demande d'ami rejetée !",
        save_changes: "Enregistrer les modifications",
        //Langues
        english: "Anglais",
        french: "Français",
        spanish: "Espagnol",
        //Modes de jeu
        tournament: "Tournoi",
        quick_match: "Partie rapide",
        enter_player_name: "Entrez le nom du joueur",
        how_many_players: "Combien de joueur(s) :",
        semifinal_1: "Demi-finale 1",
        semifinal_2: "Demi-finale 2",
        player_1: "Joueur 1",
        player_2: "Joueur 2",
        player_3: "Joueur 3",
        player_4: "Joueur 4",
        champion: "Champion",
        play: "JOUER",
        ready: "PRÊT",
        //Erreur s et messages de succès
        failed_update_avatar: "Echec du changement d'avatar",
        user_not_found: "Utilisateur introuvable",
        no_match_history: "Aucun historique de matchs pour le moment",
        failed_fetch_history: "Echec de la recuperation de l'historique des matchs",
        invalid_username: "Nom d'utilisateur invalide",
        invalid_email: "Email invalide",
        failed_accept_request: "Echec de l'acceptation de la demande",
        invalid_password_format: "Le mot de passe doit contenir 8 caractères, une lettre majuscule et un chiffre, et aucun espace n'est autorisé",
        username_or_email_taken: "Le nom d'utilisateur ou l'email est déjà pris",
        passwords_do_not_match: "Les mots de passe ne correspondent pas",
        failed_reject_request: "Echec du rejet de la demande",
        must_login: "Vous devez être connecté",
        failed_remove_friend: "Echec de la suppression d'ami",
        server_error_prefix: "Erreur serveur :",
        profile_not_found: "Profile introuvable",
        profile_updated: "Profil mis à jour !",
        missing_user_id: "Erreur : ID utilisateur introuvable",
        network_error: "Erreur réseau",
        failed_fetch_friends: "Echec de la recuperation des amis",
        logout_missing_user_id: "Impossible de se déconnecter : ID utilisateur manquant. Veuillez rafraîchir la page et réessayer.",
        logout_success: "Déconnexion réussie",
        logout_user_not_found: "Déconnexion : utilisateur introuvable sur le serveur — session locale supprimée.",
        logout_error: "Erreur lors de la déconnexion :",
        error_404_title: "Page introuvable",
        error_404_text: "La page que vous recherchez n'existe pas.",
        user_no_password: "L'utilisateur n'a pas de mot de passe (compte OAuth)"
    },
    es: {
        //Registro, Inicio de sesión
        register: "Registrar",
        registering: "Registrando...",
        register_ok: "¡Registro exitoso! Ahora puedes iniciar sesión.",
        login: "Iniciar sesión",
        logging_in: "Iniciando sesión...",
        logout: "Cerrar sesión",
        profile: "Perfil",
        match_history: "Historial de partidas",
        language: "Idioma",
        invalid_user_or_password: "Usuario o contraseña inválida",
        invalid_user_or_email: "Usuario o correo electrónico inválido",
        invalid_password: "Contraseña inválida",
        login_success: "Inicio de sesión exitoso",
        oauth42: "Iniciar sesion con 42",
        //Perfil de usuario y lobby de juego
        logout_btn: "Cerrar sesion",
        username: "Usuario",
        new_username: "Nuevo nombre de usuario",
        avatar: "Avatar",
        new_avatar: "Nueva URL del avatar",
        change_avatar: "Cambiar avatar",
        upload_avatar: "Subir avatar",
        password: "Contraseña",
        new_password: "Nueva contraseña",
        email: "Correo electrónico",
        new_email: "Nuevo correo electrónico",
        confirm_password: "Confirmar contraseña",
        submit: "Enviar",
        edit_profile: "Editar perfil",
        edit: "Editar",
        stats: "Estadísticas",
        victories: "Victorias",
        defeats: "Derrotas",
        win_tournament: " ganó el torneo!",
        win_this: " ganar con",
        point: " punto(s)!",
        //2FA + Mensajes
        draw: "Empate",
        two_factor_authentication: "2FA Autenticación",
        enable_2fa: "Activar 2FA",
        disable_2fa: "Desactivar 2FA",
        failed_enable: "Error al activar 2FA. Por favor, intentalo de nuevo.",
        enter_2fa: "Introduce tu código de autenticación",
        verify: "Verificar",
        enter_email_2fa: "Introduce tu correo para la 2FA",
        error_qr: "Servidor no devolvio el codigo QR",
        scan_qr: "Escaneo el codigo QR e introduce el codigo generado...",
        enter_phone_2fa: "Introduce tu número de teléfono",
        no_value_provided: "Por favor introduce un valor.",
        error_prefix: "Error: ",
        missing_2fa_code: "Falta el codigo 2FA.",
        two_fa_enabled_success: "¡2FA activada con éxito!",
        two_fa_is_enabled: "La 2FA está activada",
        disable: "Desactivar",
        two_fa_setup_in_progress: "Configuración de 2FA en progreso...",
        cancel: "Cancelar",
        enabled: "Activada",
        two_fa_is_disabled: "La 2FA está desactivada.",
        enable: "Activar",
        code_must_be_six_digits: "El código debe contener exactamente 6 dígitos.",
        scan_qr_warning: "Asegúrate de escanear el código QR con Google Authenticator antes de actualizar o salir de la página.",
        scan_qr_instruction: "Escanea el código QR e introduce el código generado. Guárdalo en tu Google Authenticator para futuros inicios de sesión.",
        qr_activation_error: "Error activando el código QR.",
        method_not_selected: "No se seleccionó ningún método 2FA.",
        two_fa_required: "2FA requerida",
        twofa_not_init: "Modulo 2FA no inicializado. Llama a init2FA() primero.",
        enter_2fa_code: "Introduce el código 2FA",
        six_numbers_requiered: "El código debe contener exactamente 6 dígitos.",
        login_success_2fa: "¡Inicio de sesión exitoso con 2FA!",
        only_png: "Solo se permiten imágenes PNG.",
        image_too_heavy: "La imagen es demasiado pesada (máx 2MB).",
        //Amigos
        friends: "Amigos",
        friend_list: "Lista de amigos",
        add_friend: "Añadir amigo",
        your_friends: "Tus amigos",
        pending_friends: "Amigos pendientes",
        remove_friend: "Eliminar amigo",
        ask_username: "Introduce el nombre de usuario del amigo a anadir:",
        friend_request_sent: "¡Solicitud de amigo enviada!",
        failed_friend_request: "Error al enviar la solicitud de amigo",
        cannot_send_request_to_yourself: "No puedes enviarte una solicitud de amigo a ti mismo",
        friend_request_already_exists: "La solicitud de amigo ya existe",
        already_friends: "Ya son amigos",
        no_friends_yet: "Aun no hay amigos",
        no_pending_requests: "No hay solicitudes pendientes",
        save_changes: "Guardar cambios",
        friends_request_accepted: "¡Solicitud de amigo aceptada!",
        friends_request_rejected: "¡Solicitud de amigo rechazada!",
        //Idiomas
        english: "Inglés",
        french: "Francés",
        spanish: "Español",
        //Modos de juego
        tournament: "Torneo",
        quick_match: "Partida rápida",
        enter_player_name: "Ingresa el nombre del jugador",
        how_many_players: "¿Cuántos jugadores?",
        semifinal_1: "Semifinal 1",
        semifinal_2: "Semifinal 2",
        player_1: "Jugador 1",
        player_2: "Jugador 2",
        player_3: "Jugador 3",
        player_4: "Jugador 4",
        champion: "Campeón",
        play: "JUGAR",
        ready: "LISTO",
        //Errores y mensajes de éxito
        failed_update_avatar: "Error al cambiar el avatar",
        user_not_found: "Usuario no encontrado",
        no_match_history: "No hay partidas aun",
        failed_fetch_history: "Error al obtener el historial de partidas",
        invalid_username: "Usuario inválido",
        invalid_email: "Correo inválido",
        invalid_password_format: "La contraseña debe tener 8 caracteres, incluida una letra mayúscula y un número, sin espacios.",
        username_or_email_taken: "El nombre de usuario o el correo ya están en uso",
        passwords_do_not_match: "Las contraseñas no coinciden",
        failed_accept_request: "Error al aceptar la solicitud",
        failed_reject_request: "Error al rechazar la solicitud",
        must_login: "Debes estar conectado",
        server_error_prefix: "Error del servidor:",
        profile_not_found: "Perfil no encontrado",
        profile_updated: "¡Perfil actualizado!",
        missing_user_id: "Error: no se encontró el ID del usuario",
        network_error: "Error de red",
        failed_remove_friend: "Error al eliminar amigo",
        failed_fetch_friends: "Error al obtener amigos",
        logout_missing_user_id: "No se puede cerrar sesión: falta el ID de usuario. Recarga la página e inténtalo de nuevo.",
        logout_success: "Cierre de sesión exitoso",
        logout_user_not_found: "Cierre de sesión: usuario no encontrado en el servidor — sesión local eliminada.",
        logout_error: "Error al cerrar sesión:",
        error_404_title: "Página no encontrada",
        error_404_text: "La página que buscas no existe.",
        user_no_password: "El usuario no tiene contraseña (cuenta OAuth)"
    },
};
