const translations = {
	en: {
		register: "Register",
		login: "Login",
		editProfile: "Edit Profile",
		friends: "Friends",
		matchHistory: "Match History",
		logout: "Logout",
		language: "Language",
		username: "Username",
		email: "Email",
		password: "Password",
		confirmPassword: "Confirm Password",
		registrationSuccess: "Registration successful! You can now log in.",
		invalidEmail: "Invalid email",
		passwordRequirements: "Password must have 8 characters, one uppercase letter and one number",
		invalidUsername: "Invalid username",
		passwordsNotMatch: "Passwords do not match",
		errors: "Errors",
		registering: "Registering...",
		loginId: "Username or Email",
		loggingIn: "Logging in...",
		logoutSuccess: "Logout successful",
		errorLoggingOut: "Error logging out",
		networkError: "Network error. Try again later."
	},

	fr: {
		register: "S'inscrire",
		login: "Connexion",
		editProfile: "Modifier le profil",
		friends: "Amis",
		matchHistory: "Historique des matchs",
		logout: "Déconnexion",
		language: "Langue",
		username: "Nom d'utilisateur",
		email: "Email",
		password: "Mot de passe",
		confirmPassword: "Confirmer le mot de passe",
		registrationSuccess: "Inscription réussie ! Vous pouvez maintenant vous connecter.",
		invalidEmail: "Email invalide",
		passwordRequirements: "Le mot de passe doit avoir 8 caractères, une majuscule et un chiffre",
		invalidUsername: "Nom d'utilisateur invalide",
		passwordsNotMatch: "Les mots de passe ne correspondent pas",
		errors: "Erreurs",
		registering: "Inscription en cours...",
		loginId: "Nom d'utilisateur ou Email",
		loggingIn: "Connexion en cours...",
		logoutSuccess: "Déconnexion réussie",
		errorLoggingOut: "Erreur lors de la déconnexion",
		networkError: "Erreur réseau. Réessayez plus tard.",
	},

	es: {

		register: "Registrarse",
		login: "Iniciar sesión",
		editProfile: "Editar perfil",
		friends: "Amigos",
		matchHistory: "Historial de partidas",
		logout: "Cerrar sesión",
		language: "Idioma",
		username: "Nombre de usuario",
		email: "Correo electrónico",
		password: "Contraseña",
		confirmPassword: "Confirmar contraseña",
		registrationSuccess: "¡Registro exitoso! Ahora puede iniciar sesión.",
		invalidEmail: "Email inválido",
		passwordRequirements: "La contraseña debe tener 8 caracteres, una mayúscula y un número",
		invalidUsername: "Nombre de usuario inválido",
		passwordsNotMatch: "Las contraseñas no coinciden",
		errors: "Errores",
		registering: "Registrando...",
		loginId: "Nombre de usuario o correo",
		loggingIn: "Iniciando sesión...",
		logoutSuccess: "Sesión cerrada exitosamente",
		errorLoggingOut: "Error al cerrar sesión",
		networkError: "Error de red. Inténtelo más tarde.",
	}
};

let currentLang = localStorage.getItem('lang') || 'en';